2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Configure stats pid to 19766
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Loading settings from /home/iarroyof/.config/wandb/settings
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Loading settings from /home/iarroyof/Projects/ov-llm-reasoning/wandb/settings
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'red_neuronal_utm', 'project': 'huggingface', 'sweep_id': 'ax07lpd4', 'root_dir': '/home/iarroyof/Projects/ov-llm-reasoning', 'run_id': 'cwkrp36o', 'sweep_param_path': '/home/iarroyof/Projects/ov-llm-reasoning/wandb/sweep-ax07lpd4/config-cwkrp36o.yaml'}
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'seq2seq_T5.py', 'program_abspath': '/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py', 'program': '/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py'}
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:_log_setup():521] Logging user logs to /home/iarroyof/Projects/ov-llm-reasoning/wandb/run-20240430_200210-cwkrp36o/logs/debug.log
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:_log_setup():522] Logging internal logs to /home/iarroyof/Projects/ov-llm-reasoning/wandb/run-20240430_200210-cwkrp36o/logs/debug-internal.log
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():561] calling init triggers
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():568] wandb.init called with sweep_config: {'batch_size': 4, 'epochs': 8, 'learning_rate': 0.0001, 'optimizer': 'adamw'}
config: {}
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():611] starting backend
2024-04-30 20:02:10,457 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():615] setting up manager
2024-04-30 20:02:10,462 INFO    Thread-2 (_run_job):19766 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-30 20:02:10,463 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():623] backend started and connected
2024-04-30 20:02:10,467 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_config_callback():1347] config_cb None None {'batch_size': 4, 'epochs': 8, 'learning_rate': 0.0001, 'optimizer': 'adamw'}
2024-04-30 20:02:10,467 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():715] updated telemetry
2024-04-30 20:02:10,473 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-30 20:02:10,728 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_on_init():2357] communicating current version
2024-04-30 20:02:11,009 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_on_init():2366] got version response 
2024-04-30 20:02:11,010 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():799] starting run threads in backend
2024-04-30 20:02:12,157 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_console_start():2335] atexit reg
2024-04-30 20:02:12,157 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-30 20:02:12,157 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-30 20:02:12,157 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-30 20:02:12,158 INFO    Thread-2 (_run_job):19766 [wandb_init.py:init():842] run started, returning control to user process
2024-04-30 20:02:16,985 INFO    Thread-2 (_run_job):19766 [wandb_watch.py:watch():51] Watching
2024-04-30 23:14:19,441 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_finish():2064] finishing run red_neuronal_utm/huggingface/cwkrp36o
2024-04-30 23:14:19,441 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 1
2024-04-30 23:14:19,441 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_restore():2287] restore
2024-04-30 23:14:19,441 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_restore():2293] restore done
2024-04-30 23:14:23,444 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_restore():2287] restore
2024-04-30 23:14:23,444 INFO    Thread-2 (_run_job):19766 [wandb_run.py:_restore():2293] restore done
2024-04-30 23:14:24,448 ERROR   Thread-2 (_run_job):19766 [wandb_run.py:_atexit_cleanup():2325] Problem finishing run
Traceback (most recent call last):
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 253, in main
    reasoning_pipeline.test(val_loader, epoch)
  File "/home/iarroyof/Projects/ov-llm-reasoning/seq2seq_T5.py", line 76, in test
    print(f"Epoch: {epoch} | Test Loss: {loss} | Test score ({self.score_type}): {test_score}")
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 640, in write
    self._old_write(data)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2313, in _atexit_cleanup
    self._on_finish()
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2561, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 303, in wait
    on_progress(progress_handle)
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2540, in _on_progress_exit
    self._footer_file_pusher_status_info(
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3749, in _footer_file_pusher_status_info
    Run._footer_single_run_file_pusher_status_info(
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3800, in _footer_single_run_file_pusher_status_info
    printer.progress_update(line, percent_done)
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/sdk/lib/printer.py", line 172, in progress_update
    wandb.termlog(f"{next(self._progress)} {text}", newline=False)
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/errors/term.py", line 39, in termlog
    _log(
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/iarroyof/miniconda3/envs/pt/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error
